program Gestao;

{$IFDEF RELEASE}
  {$STACKFRAMES ON}
{$ENDIF}

//{$i app_linker.inc}

uses
  {$IFDEF DEBUG}
  FastMM4,
  {$ENDIF }
  {$IFDEF UNICODE}
  {$IFNDEF FPC}
  uFxtDelayedHandler in 'componentes\uFxtDelayedHandler.pas',
  {$ENDIF }
  {$ENDIF }
  libssh2 in 'componentes\libssh2.pas',
  libssh2_publickey in 'componentes\libssh2_publickey.pas',
  libssh2_sftp in 'componentes\libssh2_sftp.pas',
  uMySFTPClient in 'componentes\uMySFTPClient.pas',
  Windows,
  Messages,
  SysUtils,
  Classes,
  Vcl.Graphics,
  Vcl.Controls,
  Vcl.Forms,
  Vcl.Dialogs,
  Winapi.ShellAPI,
  midaslib,
  Un_DM in 'Tarefas\Un_DM.pas' {DM: TDataModule},
  UN_TabelasEmListas in 'Tarefas\UN_TabelasEmListas.pas' {DM_ListaConsultas: TDataModule},
  UN_Principal in 'Tarefas\UN_Principal.pas' {Fr_Principal},
  UN_SPLASH in 'Ajuda\UN_SPLASH.pas' {SplashForm},
  UN_Sistema,
  Un_Fm_CardapioPanel in 'Frames\Un_Fm_CardapioPanel.pas' {Fm_CardapioPanel: TFrame},
  Un_Fm_Cardapio in 'Frames\Un_Fm_Cardapio.pas' {Fm_Cardapio: TFrame},
  Un_Fm_CardapioMT in 'Frames\Un_Fm_CardapioMT.pas' {Fm_CardapioMT: TFrame},
  Un_Fm_Itens_Pedido in 'Frames\Un_Fm_Itens_Pedido.pas' {Fm_Itens_Pedido: TFrame},
  Un_Fm_ListaEmpresaEndereco in 'Frames\Un_Fm_ListaEmpresaEndereco.pas' {Fm_ListaEmpresaEndereco: TFrame},
  Un_Fm_ListaProdutos in 'Frames\Un_Fm_ListaProdutos.pas' {Fm_ListaProdutos: TFrame},
  Un_Fm_ListaTabelaPreco in 'Frames\Un_Fm_ListaTabelaPreco.pas' {Fm_ListaTabelaPreco: TFrame},
  Un_Fm_ListaUsuarios in 'Frames\Un_Fm_ListaUsuarios.pas' {Fm_ListaUsuarios: TFrame},
  Un_Fm_MetodoPagamento in 'Frames\Un_Fm_MetodoPagamento.pas' {Fm_MetodoPagamento: TFrame},
  Un_Fm_FormaPagto in 'Frames\Un_Fm_FormaPagto.pas' {Fm_FormaPagto: TFrame},
  Un_Fm_MetodoPagamentoParcelado in 'Frames\Un_Fm_MetodoPagamentoParcelado.pas' {Fm_MetodoPagamentoParcelado: TFrame},
  Un_Fm_ListaEstoques in 'Frames\Un_Fm_ListaEstoques.pas' {Fm_ListaEstoques: TFrame},
  Un_Fm_ListaGrupoSubGrupo in 'Frames\Un_Fm_ListaGrupoSubGrupo.pas' {Fm_ListaGrupoSubGrupo: TFrame},
  Un_fm_ListaTributacao in 'Frames\Un_fm_ListaTributacao.pas' {fm_ListaTributacao: TFrame},
  un_fm_lista_pet in 'Frames\un_fm_lista_pet.pas' {Fm_ListaPet: TFrame},
  Un_Fm_CentroResultado in 'Frames\Un_Fm_CentroResultado.pas' {Fm_CentroResultado: TFrame},
  Un_Fm_CentroCusto in 'Frames\Un_Fm_CentroCusto.pas' {Fm_CentroCusto: TFrame},
  Un_Fm_ListaFornecedores in 'Frames\Un_Fm_ListaFornecedores.pas' {Fm_ListaFornecedores: TFrame},
  Un_Fm_ListaEmpresas in 'Frames\Un_Fm_ListaEmpresas.pas' {Fm_ListaEmpresas: TFrame},
  Un_Fm_ListaSituacao in 'Frames\Un_Fm_ListaSituacao.pas' {Fm_ListaSituacao: TFrame},
  Un_Fm_ListaHistoricoBancario in 'Frames\Un_Fm_ListaHistoricoBancario.pas' {Fm_ListaHistoricoBancario: TFrame},
  Un_Fm_ListaMarcaProduto in 'Frames\Un_Fm_ListaMarcaProduto.pas' {Fm_ListaMarcaProduto: TFrame},
  Un_Fm_ListaTecnicos in 'Frames\Un_Fm_ListaTecnicos.pas' {Fm_ListaTecnicos: TFrame},
  Un_Fm_ListaColaboradores in 'Frames\Un_Fm_ListaColaboradores.pas' {Fm_ListaColaboradores: TFrame},
  Un_Fm_ListaMultiEmpresa in 'Frames\Un_Fm_ListaMultiEmpresa.pas' {Fm_ListaMultiEmpresa: TFrame},
  un_fm_billing_portfolio in 'Frames\un_fm_billing_portfolio.pas' {FmBillingPortfolio: TFrame},
  Un_Fm_ListaEspecieDoc in 'Frames\Un_Fm_ListaEspecieDoc.pas' {Fm_ListaEspecieDoc: TFrame},
  Un_Fm_ListaContaBancaria in 'Frames\Un_Fm_ListaContaBancaria.pas' {Fm_ListaContaBancaria: TFrame},
  Un_Fm_CardapioMTP in 'Frames\Un_Fm_CardapioMTP.pas' {Fm_CardapioMTP: TFrame},
  Un_Fm_CardapioMTS in 'Frames\Un_Fm_CardapioMTS.pas' {Fm_CardapioMTS: TFrame},
  Un_Fm_CardapioUT in 'Frames\Un_Fm_CardapioUT.pas' {Fm_CardapioUT: TFrame},
  Un_fm_listaCidade in 'Frames\Un_fm_listaCidade.pas' {FmListaCidades: TFrame},
  Un_Fm_ListaClientes in 'Frames\Un_Fm_ListaClientes.pas' {Fm_ListaClientes: TFrame},
  Un_Fm_PizzariaMTP in 'Frames\Un_Fm_PizzariaMTP.pas' {Fm_PizzariaMTP: TFrame},
  fm_itens_importa_xml in 'Frames\fm_itens_importa_xml.pas' {FmItensImportaXml: TFrame},
  un_frx_ReportCtaReceber in 'FastReport\un_frx_ReportCtaReceber.pas' {frx_ReportCtaReceber},
  Un_RL_Report in 'repository\Un_RL_Report.pas' {RL_Report},
  Un_base_Pesq in 'repository\Un_base_Pesq.pas' {Fr_Base_Pesq},
  Un_RL_ReportBudget in 'repository\Un_RL_ReportBudget.pas' {RL_ReportBudget},
  Un_RL_ReportList in 'repository\Un_RL_ReportList.pas' {RL_ReportList},
  Un_RL_ReportOrder in 'repository\Un_RL_ReportOrder.pas' {RL_ReportOrder},
  Un_RL_ReportProduct in 'repository\Un_RL_ReportProduct.pas' {RL_ReportProduct},
  tas_config in 'Ajuda\tas_config.pas' {TasConfig},
  un_geranfe3X in 'Ajuda\un_geranfe3X.pas' {Fr_GeraNfe3x},
  Un_Pesq_NotaFiscal in 'repository\Un_Pesq_NotaFiscal.pas' {Fr_Pesq_NotaFiscal},
  un_func_img_button in 'Funcao\un_func_img_button.pas',
  env in 'env.pas',
  Un_Cupom_Fiscal in 'Tarefas\Un_Cupom_Fiscal.pas' {Fr_Cupom_Fiscal},
  sea_job_position in 'view\module\human_resource\register\sea_job_position.pas' {SeaJobPosition},
  reg_job_position in 'view\module\human_resource\register\reg_job_position.pas' {RegJobPosition},
  reg_printers in 'view\module\operation\admin\reg_printers.pas' {RegPrinters},
  reg_virtual_shop in 'view\module\operation\admin\reg_virtual_shop.pas' {RegVirtualShop},
  sea_printers in 'view\module\operation\admin\sea_printers.pas' {SeaPrinters},
  sea_users in 'view\module\operation\admin\sea_users.pas' {SeaUsers},
  reg_city in 'view\module\operation\register\reg_city.pas' {RegCity},
  sea_city in 'view\module\operation\register\sea_city.pas' {SeaCity},
  reg_commitment in 'view\module\operation\admin\reg_commitment.pas' {RegCommitment},
  Un_Pedido_Vda in 'Tarefas\Un_Pedido_Vda.pas' {Fr_Pedido_Vda},
  Un_Nota_Fiscal in 'Tarefas\Un_Nota_Fiscal.pas' {Fr_Nota_Fiscal},
  base_config in 'repository\base_config.pas' {Fr_Base_Config},
  base_download in 'repository\base_download.pas' {BaseDonwload},
  base_registry in 'view\inheritable\base_registry.pas' {BaseRegistry},
  base_search in 'view\inheritable\base_search.pas' {BaseSearch},
  tas_lanca_item_produto in 'repository\tas_lanca_item_produto.pas' {TasLancaItemProdutos},
  sea_receipt in 'Tarefas\sea_receipt.pas' {SeaReceipt},
  reg_receipt in 'Tarefas\reg_receipt.pas' {RegReceipt},
  Un_Cotacao in 'Tarefas\Un_Cotacao.pas' {Fr_Cotacao},
  UN_Fatura_Vda in 'Tarefas\UN_Fatura_Vda.pas' {Fr_Fatura_Vda},
  UN_Pedido_Cpa in 'Tarefas\UN_Pedido_Cpa.pas' {Fr_Pedido_Cpa},
  UN_Pedido_Ajt in 'Tarefas\UN_Pedido_Ajt.pas' {Fr_Pedido_Ajt},
  Un_Fich_Fin_Cli in 'Tarefas\Un_Fich_Fin_Cli.pas' {Fr_Fich_Fin_Cli},
  Un_Fich_Fin_For in 'Tarefas\Un_Fich_Fin_For.pas' {Fr_Fich_Fin_For},
  Un_MalaDiretaEMail in 'Tarefas\Un_MalaDiretaEMail.pas' {Fr_MalaDiretaEMail},
  Un_Clta_Mov_Produtos in 'Tarefas\Un_Clta_Mov_Produtos.pas' {Fr_Clta_Mov_Produtos},
  Un_Empresa in 'repository\Un_Empresa.pas' {Fr_Empresa},
  Un_Itens_Produto in 'Tarefas\Un_Itens_Produto.pas' {Fr_Itens_Produto},
  Un_Itens_Produto_Vda in 'Tarefas\Un_Itens_Produto_Vda.pas' {Fr_Itens_Produto_Vda},
  reg_banking_account in 'view\module\banking\register\reg_banking_account.pas' {RegBankingAccount},
  reg_banking_history in 'view\module\banking\register\reg_banking_history.pas' {RegBankingHistory},
  reg_billing_portfolio in 'view\module\banking\register\reg_billing_portfolio.pas' {RegBillingPortfolio},
  reg_electronic_card in 'view\module\banking\register\reg_electronic_card.pas' {RegElectronicCard},
  reg_electronic_slip in 'view\module\banking\register\reg_electronic_slip.pas' {RegElectronicSlip},
  sea_banking_history in 'view\module\banking\register\sea_banking_history.pas' {SeaBankingHistory},
  sea_electronic_slip in 'view\module\banking\register\sea_electronic_slip.pas' {SeaElectronicSlip},
  un_tray_to_gestao in 'Roteador\function\un_tray_to_gestao.pas',
  un_base_tray in 'Roteador\function\un_base_tray.pas',
  Un_Funcoes in 'Funcao\Un_Funcoes.pas',
  sea_banking_account in 'view\module\banking\register\sea_banking_account.pas' {SeaBankingAccount},
  Un_ContasCorrente in 'Tarefas\Un_ContasCorrente.pas' {Fr_ContasCorrente},
  Un_Lanca_Banco in 'Tarefas\Un_Lanca_Banco.pas' {Fr_Lanca_Banco},
  Un_Lanca_Caixa in 'Tarefas\Un_Lanca_Caixa.pas' {Fr_Lanca_Caixa},
  Un_Lanca_Command in 'Tarefas\Un_Lanca_Command.pas' {Fr_Lanca_Command},
  Un_Lanca_Despacho in 'Tarefas\Un_Lanca_Despacho.pas' {Fr_Lanca_Despacho},
  UN_Lanca_Pagto in 'Tarefas\UN_Lanca_Pagto.pas' {Fr_Lanca_Pagto},
  Un_Lanca_PlanoContas in 'Tarefas\Un_Lanca_PlanoContas.pas' {Fr_Lanca_PlanoContas},
  Un_Pagar_Multipla in 'Tarefas\Un_Pagar_Multipla.pas' {Fr_Pagar_Multipla},
  UN_Receber_Multipla in 'Tarefas\UN_Receber_Multipla.pas' {Fr_Receber_Multipla},
  UN_Imp_Lucratividade in 'Relatorios\UN_Imp_Lucratividade.pas' {Fr_Imp_Lucratividade},
  Un_Produtos in 'Arquivos\Un_Produtos.pas' {Fr_Produtos},
  UN_Imp_Produtos in 'Relatorios\UN_Imp_Produtos.pas' {Fr_Imp_Produtos},
  un_estoque_manual in 'Tarefas\un_estoque_manual.pas' {Fr_Estoque_manual},
  Un_Configuracao in 'Ajuda\Un_Configuracao.pas' {Fr_Configuracao},
  Un_Atualiza in 'Ajuda\Un_Atualiza.pas' {Fr_Atualiza},
  sea_package in 'view\module\operation\register\sea_package.pas' {SeaPackage},
  reg_package in 'view\module\operation\register\reg_package.pas' {RegPackage},
  ControllerEmbalagem in 'Controller\ControllerEmbalagem.pas',
  sea_uf in 'view\module\operation\register\sea_uf.pas' {SeaUf},
  reg_uf in 'view\module\operation\register\reg_uf.pas' {RegUf},
  tblFcpUfNcm in 'model\tblFcpUfNcm.pas',
  tblMvaUfNcm in 'model\tblMvaUfNcm.pas',
  ControllerFcpUfNcm in 'Controller\ControllerFcpUfNcm.pas',
  ControllerMvaUfNcm in 'Controller\ControllerMvaUfNcm.pas',
  prm_mva_uf_ncm in 'Parametros\prm_mva_uf_ncm.pas',
  prm_fcp_uf_ncm in 'Parametros\prm_fcp_uf_ncm.pas',
  Un_Especie_Doc in 'Arquivos\Un_Especie_Doc.pas' {Fr_Especie_Doc},
  Un_Info_Compra_Venda in 'Tarefas\Un_Info_Compra_Venda.pas' {Fr_Info_Compra_Venda},
  reg_users in 'view\module\operation\admin\reg_users.pas' {RegUsers},
  tblSendWhatsApp in 'model\tblSendWhatsApp.pas',
  ControllerSendWhatsApp in 'Controller\ControllerSendWhatsApp.pas',
  UnGeraLog in 'Funcao\UnGeraLog.pas',
  reg_interface in 'view\module\operation\register\reg_interface.pas' {RegInterface},
  sea_interface in 'view\module\operation\register\sea_interface.pas' {SeaInterface},
  Un_envia_email in 'view\module\operation\admin\Un_envia_email.pas' {Fr_envia_email},
  tblItensIFC in 'model\tblItensIFC.pas',
  tas_notification in 'view\module\operation\admin\tas_notification.pas' {TasNotification},
  tas_notification_item in 'view\module\operation\admin\tas_notification_item.pas' {TasNotificationItem: TFrame},
  UN_RL_OS_Extintor in 'Relatorios\UN_RL_OS_Extintor.pas' {RL_OS_Extintor},
  Un_RL_MovimentoProduto in 'Relatorios\Un_RL_MovimentoProduto.pas' {RL_MovimentoProduto},
  Un_ContasReceberBoleto in 'Tarefas\Un_ContasReceberBoleto.pas' {Fr_ContasReceberBoleto},
  UN_Fatura_Ajt in 'Tarefas\UN_Fatura_Ajt.pas' {Fr_Fatura_Ajt},
  Un_Agenda in 'Ajuda\Un_Agenda.pas' {Fr_Agenda},
  un_geranfe_Srv in 'Ajuda\un_geranfe_Srv.pas' {Fr_geranfe_Srv},
  reg_collaborator in 'view\module\human_resource\register\reg_collaborator.pas' {RegCollaborator},
  sea_collaborator in 'view\module\human_resource\register\sea_collaborator.pas' {SeaCollaborator},
  base_frame_list in 'view\inheritable\base_frame_list.pas' {BaseFrameList: TFrame},
  Un_Pesq_Produto in 'Tarefas\Un_Pesq_Produto.pas' {Fr_Pesq_Produto},
  reg_quotation_log in 'view\module\operation\admin\reg_quotation_log.pas' {RegQuotationLog},
  Un_Fc_Sored_Procedures in 'Funcao\Un_Fc_Sored_Procedures.pas',
  sea_pay_back in 'Tarefas\sea_pay_back.pas' {SeaPayBack},
  Un_ImportaXMLNFe in 'Tarefas\Un_ImportaXMLNFe.pas' {Fr_ImportaXMLNFe},
  tblProdProd in 'model\tblProdProd.pas',
  ControllerReposicao in 'Controller\ControllerReposicao.pas',
  reg_produto_reposicao in 'view\module\operation\register\reg_produto_reposicao.pas' {RegProdutoReposicao},
  Un_Composicao in 'Arquivos\Un_Composicao.pas' {Fr_Composicao},
  Un_Caixa in 'Tarefas\Un_Caixa.PAS' {Fr_Caixa},
  rg_privilege in 'view\module\operation\register\rg_privilege.pas' {RgPrivilege},
  sea_profile in 'view\module\operation\register\sea_profile.pas' {SeaProfile},
  reg_profile in 'view\module\operation\register\reg_profile.pas' {RegProfile},
  sea_oper_interface in 'view\module\operation\register\sea_oper_interface.pas' {SeaOperInterface},
  reg_oper_interface in 'view\module\operation\register\reg_oper_interface.pas' {RegOperInterface},
  reg_business in 'view\module\operation\register\reg_business.pas' {RegBusiness},
  sea_business in 'view\module\operation\register\sea_business.pas' {SeaBusiness},
  Un_Clta_Negocio in 'Tarefas\Un_Clta_Negocio.pas' {Fr_Clta_Negocio},
  reg_config_tag in 'view\module\operation\admin\reg_config_tag.pas' {RegConfigTag},
  sea_config_tag in 'view\module\operation\admin\sea_config_tag.pas' {SeaConfigTag},
  reg_vehicle_brand in 'view\module\operation\register\reg_vehicle_brand.pas' {RegVehicleBrand},
  reg_vehicle_model in 'view\module\operation\register\reg_vehicle_model.pas' {RegVehicleModel},
  sea_note in 'view\module\operation\register\sea_note.pas' {SeaNote},
  reg_note in 'view\module\operation\register\reg_note.pas' {RegNote},
  setes_forms in 'Funcao\setes_forms.pas',
  Un_Cardapio in 'Arquivos\Un_Cardapio.pas' {Fr_Cardapio},
  reg_subgroup_menu in 'view\module\operation\register\reg_subgroup_menu.pas' {RegSubgroupMenu},
  reg_group in 'view\module\operation\register\reg_group.pas' {RegGroup},
  sea_Mdfe in 'Tarefas\sea_Mdfe.pas' {SeaMdfe},
  tas_mdfe in 'Ajuda\tas_mdfe.pas' {TasMdfe},
  tas_mdfe_operacoes in 'Ajuda\tas_mdfe_operacoes.pas' {TasMdfeOperacoes},
  tas_mdfe_config in 'Ajuda\tas_mdfe_config.pas' {TasMdfeConfig},
  tblNfEletronica in 'model\tblNfEletronica.pas',
  ControllerNfEletronica in 'Controller\ControllerNfEletronica.pas',
  prm_nf_eletronica in 'Parametros\prm_nf_eletronica.pas',
  tas_gera_nfe_config in 'view\module\operation\task\tas_gera_nfe_config.pas' {TasGeraNfeConfig},
  tas_gera_nfe_operacao in 'view\module\operation\task\tas_gera_nfe_operacao.pas' {TasGeraNfeOperacao},
  tas_gera_nfe_inutiliza in 'view\module\operation\task\tas_gera_nfe_inutiliza.pas' {TasGeraNfeInutiliza},
  tas_gera_nfe_schemas in 'view\module\operation\task\tas_gera_nfe_schemas.pas' {TasGeraNfeSchemas},
  un_geranfe_ajt in 'Ajuda\un_geranfe_ajt.pas' {Fr_GeraNfe_Ajt},
  un_geranfe_vda in 'Ajuda\un_geranfe_vda.pas' {Fr_GeraNfe_vda},
  tas_gera_nfce_autorizacao_lote in 'view\module\operation\task\tas_gera_nfce_autorizacao_lote.pas' {TasGeraNfceAutorizacaoLote},
  tas_gera_nfce_autorizacao in 'view\module\operation\task\tas_gera_nfce_autorizacao.pas' {TasGeraNfceAutorizacao},
  un_geranfe_cpa in 'Ajuda\un_geranfe_cpa.pas' {Fr_geranfe_cpa},
  tas_gera_nfce_operacao in 'view\module\operation\task\tas_gera_nfce_operacao.pas' {TasGeraNfceOperacao},
  tas_gera_nfe_autorizacao in 'view\module\operation\task\tas_gera_nfe_autorizacao.pas' {TasGeraNfeAutorizacao},
  reg_customer_prospection in 'view\module\operation\register\reg_customer_prospection.pas' {RegCustomerProspection},
  Un_Pesq_Empresa in 'Tarefas\Un_Pesq_Empresa.pas' {Fr_Pesq_Empresa},
  sea_measure in 'view\module\operation\register\sea_measure.pas' {SeaMeasure},
  reg_measure in 'view\module\operation\register\reg_measure.pas' {RegMeasure},
  sea_cfop in 'view\module\operation\register\sea_cfop.pas' {SeaCfop},
  reg_cfop in 'view\module\operation\register\reg_cfop.pas' {RegCfop},
  sea_product_brand in 'view\module\operation\register\sea_product_brand.pas' {SeaProductBrand},
  reg_product_brand in 'view\module\operation\register\reg_product_brand.pas' {RegProductBrand},
  reg_general_taxes in 'view\module\operation\register\reg_general_taxes.pas' {RegGeneralTaxes},
  reg_kind_profitability in 'view\module\operation\register\reg_kind_profitability.pas' {RegKindProfitability},
  sea_vehicle_kind in 'view\module\operation\register\sea_vehicle_kind.pas' {SeaVehicleKind},
  reg_vehicle_kind in 'view\module\operation\register\reg_vehicle_kind.pas' {RegVehicleKind},
  sea_situation in 'view\module\operation\register\sea_situation.pas' {SeaSituation},
  reg_situation in 'view\module\operation\register\reg_situation.pas' {RegSituation},
  Un_Cliente in 'Arquivos\Un_Cliente.pas' {Fr_Cliente},
  sea_tax_relieves_icms in 'view\module\operation\register\sea_tax_relieves_icms.pas' {SeaTaxRelievesIcms},
  Un_Adic_Imp in 'Tarefas\Un_Adic_Imp.pas' {Fr_Adic_Imp},
  sea_vehicle_brand in 'view\module\operation\register\sea_vehicle_brand.pas' {SeaVehicleBrand},
  Un_Itens_Produto_CTC_Vda in 'Tarefas\Un_Itens_Produto_CTC_Vda.pas' {Fr_Itens_Produto_CTC_Vda},
  Un_FrenteCaixa in 'Tarefas\Un_FrenteCaixa.pas' {Fr_FrenteCaixa},
  sea_ctrl_cheque in 'view\module\operation\task\sea_ctrl_cheque.pas' {SeaCtrlCheque},
  prm_ctrl_cheque in 'Parametros\prm_ctrl_cheque.pas',
  reg_ctrl_cheque in 'view\module\operation\task\reg_ctrl_cheque.pas' {RegCtrlCheque},
  dpt_ctrl_cheque in 'view\module\financial\task\dpt_ctrl_cheque.pas' {DptCtrlCheque},
  dct_ctrl_cheque in 'view\module\financial\task\dct_ctrl_cheque.pas' {DctCtrlCheque},
  reg_correction_letter in 'view\module\operation\task\reg_correction_letter.pas' {RegCorrectionLetter},
  Un_Virtual_Shop in 'Ajuda\Un_Virtual_Shop.pas' {Fr_Virtual_Shop},
  Un_Info_Dec_Imp in 'Tarefas\Un_Info_Dec_Imp.pas' {Fr_Info_Dec_Imp},
  Un_Produto_Series in 'Tarefas\Un_Produto_Series.pas' {Fr_Produto_Serie},
  tblSerieProduto in 'model\tblSerieProduto.pas',
  ControllerSerieProduto in 'Controller\ControllerSerieProduto.pas',
  prm_serie_produto in 'Parametros\prm_serie_produto.pas',
  tblSerieVeiculo in 'model\tblSerieVeiculo.pas',
  ControllerSerieVeiculo in 'Controller\ControllerSerieVeiculo.pas',
  prm_serie_veiculo in 'Parametros\prm_serie_veiculo.pas',
  Un_Comissao in 'Tarefas\Un_Comissao.pas' {Fr_Comissao},
  prm_comissao in 'Parametros\prm_comissao.pas',
  tblOrdemServico in 'model\tblOrdemServico.pas',
  ControllerOrdemServico in 'Controller\ControllerOrdemServico.pas',
  prm_ordem_servico in 'Parametros\prm_ordem_servico.pas',
  Un_Lanca_Folha in 'Tarefas\Un_Lanca_Folha.pas' {Fr_Lanca_Folha},
  tblFolhaPagto in 'model\tblFolhaPagto.pas',
  ControllerFolhaPagto in 'Controller\ControllerFolhaPagto.pas',
  reg_plano_contas in 'view\module\financial\register\reg_plano_contas.pas' {RegPlanoContas},
  sea_coating in 'view\module\operation\register\sea_coating.pas' {SeaCoating},
  reg_coating in 'view\module\operation\register\reg_coating.pas' {RegCoating},
  reg_custo_pedido in 'view\module\operation\register\reg_custo_pedido.pas' {RegCustoPedido},
  tas_conserto in 'view\module\operation\task\tas_conserto.pas' {TasConserto},
  Un_Clta_Csto in 'Tarefas\Un_Clta_Csto.pas' {Fr_Clta_Csto},
  Un_Frete in 'Arquivos\Un_Frete.pas' {Fr_Frete},
  tblfrete in 'model\tblfrete.pas',
  ControllerFrete in 'Controller\ControllerFrete.pas',
  Un_Transportadora in 'Arquivos\Un_Transportadora.pas' {Fr_Transportadora},
  sea_electronic_card in 'view\module\banking\register\sea_electronic_card.pas' {SeaEletronicCard},
  sea_category in 'view\module\operation\register\sea_category.pas' {SeaCategory},
  reg_category in 'view\module\operation\register\reg_category.pas' {RegCategory},
  sea_kind_profitability in 'view\module\operation\register\sea_kind_profitability.pas' {Seakindprofitability},
  reg_subgroup in 'view\module\operation\register\reg_subgroup.pas' {RegSubgroup},
  Un_Ctrl_Lotes in 'Tarefas\Un_Ctrl_Lotes.pas' {Fr_Ctrl_Lote},
  Un_Imp_EtiqProdutos in 'Relatorios\Un_Imp_EtiqProdutos.pas' {Fr_Imp_EtiqProdutos},
  sea_group_menu in 'view\module\operation\register\sea_group_menu.pas' {SeaGroupMenu},
  sea_group in 'view\module\operation\register\sea_group.pas' {SeaGroup},
  reg_service in 'view\module\operation\register\reg_service.pas' {RegService},
  reg_group_menu in 'view\module\operation\register\reg_group_menu.pas' {RegGroupMenu},
  sea_service in 'view\module\operation\register\sea_service.pas' {SeaService},
  un_frx_base_report in 'FastReport\un_frx_base_report.pas' {FrxBaseReport},
  tas_production in 'Tarefas\tas_production.pas' {TasProduction},
  un_frx_ReportProducao in 'FastReport\un_frx_ReportProducao.pas' {frx_ReportProducao},
  un_frx_ReportProducaoMP in 'FastReport\un_frx_ReportProducaoMP.pas',
  sea_production in 'Tarefas\sea_production.pas' {SeaProduction},
  reg_contacts in 'view\module\operation\register\reg_contacts.pas' {RegContacts},
  reg_order_log in 'view\module\operation\register\reg_order_log.pas' {RegOrderLog},
  sea_contacts in 'view\module\operation\register\sea_contacts.pas' {SeaContacts},
  sea_dead_line in 'view\module\operation\register\sea_dead_line.pas' {SeaDeadLine},
  reg_dead_line in 'view\module\operation\register\reg_dead_line.pas' {RegDeadLine},
  sea_line_business in 'view\module\operation\register\sea_line_business.pas' {SeaLineBusiness},
  reg_line_business in 'view\module\operation\register\reg_line_business.pas' {RegLineBusiness},
  sea_sales_origin in 'view\module\operation\register\sea_sales_origin.pas' {SeaSalesOrigin},
  reg_sales_origin in 'view\module\operation\register\reg_sales_origin.pas' {RegSalesOrigin},
  sea_assistance in 'view\module\operation\task\sea_assistance.pas' {SeaAssistance},
  prm_assistance in 'Parametros\prm_assistance.pas',
  reg_assistance in 'view\module\operation\task\reg_assistance.pas' {RegAssistance},
  tblAssistenciaItens in 'model\tblAssistenciaItens.pas',
  tblFichaTecnica in 'model\tblFichaTecnica.pas',
  tblItensInd in 'model\tblItensInd.pas',
  tblCfgGrid in 'model\tblCfgGrid.pas',
  prm_assistance_itens in 'Parametros\prm_assistance_itens.pas',
  ControllerAssistenciaItens in 'Controller\ControllerAssistenciaItens.pas',
  ControllerFichaTecnica in 'Controller\ControllerFichaTecnica.pas',
  ControllerItensInd in 'Controller\ControllerItensInd.pas',
  ControllerCfgGrid in 'Controller\ControllerCfgGrid.pas',
  Un_RL_ReportCheque in 'Interface\Un_RL_ReportCheque.pas' {RL_ReportCheque},
  Un_RL_ReportChequeSimples in 'Interface\Un_RL_ReportChequeSimples.pas' {RL_ReportChequeSimples},
  Un_RL_ReportVendas in 'Interface\Un_RL_ReportVendas.pas' {RL_ReportVendas},
  Un_RL_ReportVendasGeral in 'Interface\Un_RL_ReportVendasGeral.pas' {RL_ReportVendasGeral},
  Un_VehicleSo in 'Tarefas\Un_VehicleSo.pas' {Fr_VehicleSo},
  UN_Fatura_Cpa in 'Tarefas\UN_Fatura_Cpa.pas' {Fr_Fatura_Cpa},
  Un_RL_ReportAssistencia in 'Interface\Un_RL_ReportAssistencia.pas' {RL_ReportAssistencia},
  cfg_assistance in 'view\module\operation\task\cfg_assistance.pas' {CfgAssistance},
  sea_customer_origin in 'view\module\operation\register\sea_customer_origin.pas' {SeaCustomerOrigin},
  reg_customer_origin in 'view\module\operation\register\reg_customer_origin.pas' {RegCustomerOrigin},
  Un_Pizzaria in 'Tarefas\Un_Pizzaria.pas' {Fr_Pizzaria},
  sea_stocks in 'view\module\operation\register\sea_stocks.pas' {SeaStocks},
  reg_stocks in 'view\module\operation\register\reg_stocks.pas' {RegStocks},
  sea_tax_icms_nr in 'view\module\operation\register\sea_tax_icms_nr.pas' {SeaTaxIcmsNr},
  reg_tax_icms_nr in 'view\module\operation\register\reg_tax_icms_nr.pas' {RegTaxIcmsNr},
  sea_tax_icms_sn in 'view\module\operation\register\sea_tax_icms_sn.pas' {SeaTaxIcmsSn},
  reg_tax_relieves_icms in 'view\module\operation\register\reg_tax_relieves_icms.pas' {RegTaxRelievesIcms},
  reg_tax_mode_det_bc_icms in 'view\module\operation\register\reg_tax_mode_det_bc_icms.pas' {RegTaxModeDetBcIcms},
  reg_tax_mode_det_bc_icms_st in 'view\module\operation\register\reg_tax_mode_det_bc_icms_st.pas' {RegTaxModeDetBcIcmsSt},
  sea_tax_mode_det_bc_icms in 'view\module\operation\register\sea_tax_mode_det_bc_icms.pas' {SeaTaxModeDetBcIcms},
  sea_tax_mode_det_bc_icms_st in 'view\module\operation\register\sea_tax_mode_det_bc_icms_st.pas' {SeaTaxModeDetBcIcmsSt},
  reg_tax_icms_sn in 'view\module\operation\register\reg_tax_icms_sn.pas' {RegTaxIcmsSn},
  Un_Fm_ListaEstados in 'Frames\Un_Fm_ListaEstados.pas' {Fm_ListaEstados: TFrame},
  sea_taxation in 'view\module\operation\register\sea_taxation.pas' {SeaTaxation},
  reg_taxation in 'view\module\operation\register\reg_taxation.pas' {RegTaxation},
  Un_CardapioProduto in 'Arquivos\Un_CardapioProduto.pas' {Fr_CardapioProduto},
  sea_button_image in 'view\module\operation\register\sea_button_image.pas' {SeaButtonImage},
  reg_button_image in 'view\module\operation\register\reg_button_image.pas' {RegButtonImage},
  Un_Fm_ListaMedida in 'Frames\Un_Fm_ListaMedida.pas' {Fm_ListaMedida: TFrame},
  Un_Fm_ListaUnidades in 'Frames\Un_Fm_ListaUnidades.pas' {Fm_ListaUnidades: TFrame},
  UN_Imp_Empresas in 'Relatorios\UN_Imp_Empresas.pas' {Fr_Imp_Empresa},
  UN_Aniversariante in 'Ajuda\UN_Aniversariante.pas' {Fr_Aniversariantes},
  Un_Receber_Descontada in 'Tarefas\Un_Receber_Descontada.pas' {Fr_Receber_Descontada},
  Un_Fm_ListaCFOP_UF in 'Frames\Un_Fm_ListaCFOP_UF.pas' {Fm_ListaCFOP_UF: TFrame},
  un_fm_lista_cfop in 'Frames\un_fm_lista_cfop.pas' {Fm_lista_cfop: TFrame},
  TypesCollection in 'D:\gestaoweb\controller\TypesCollection.pas',
  TypesObjectsCollection in 'D:\gestaoweb\controller\TypesObjectsCollection.pas',
  sea_loja_tray_order in 'Tarefas\sea_loja_tray_order.pas' {SeaLojaTrayOrder},
  trayThumbs in 'restClient\ApyTray\model\trayThumbs.pas',
  trayProductSoldImage in 'restClient\ApyTray\model\trayProductSoldImage.pas',
  TrayCategoryNew in 'restClient\ApyTray\model\TrayCategoryNew.pas',
  trayUrl in 'restClient\ApyTray\model\trayUrl.pas',
  trayStock in 'restClient\ApyTray\model\trayStock.pas',
  TrayProductsSold in 'restClient\ApyTray\model\TrayProductsSold.pas',
  trayCustomerProfileRelation in 'restClient\ApyTray\model\trayCustomerProfileRelation.pas',
  TrayCustomerAddressWrapper in 'restClient\ApyTray\model\TrayCustomerAddressWrapper.pas',
  TrayPayment in 'restClient\ApyTray\model\TrayPayment.pas',
  TrayPaymentWrapper in 'restClient\ApyTray\model\TrayPaymentWrapper.pas',
  TrayOrderTransaction in 'restClient\ApyTray\model\TrayOrderTransaction.pas',
  TrayPaymentMethodMessage in 'restClient\ApyTray\model\TrayPaymentMethodMessage.pas',
  TrayPaymentsNotification in 'restClient\ApyTray\model\TrayPaymentsNotification.pas',
  TrayOrderUrls in 'restClient\ApyTray\model\TrayOrderUrls.pas',
  TrayOrder in 'restClient\ApyTray\model\TrayOrder.pas',
  TrayOrderWrapper in 'restClient\ApyTray\model\TrayOrderWrapper.pas',
  OrderJsonPopulator in 'restClient\ApyTray\model\OrderJsonPopulator.pas',
  Un_Base in 'view\inheritable\Un_Base.pas' {Fr_Base},
  tas_items_sales_before in 'view\module\operation\task\tas_items_sales_before.pas' {TasItemsSalesBefore},
  Un_PizzariaHistorico in 'Tarefas\Un_PizzariaHistorico.pas' {Fr_PizzariaHistorico},
  Un_CopiaPedidoNota in 'Tarefas\Un_CopiaPedidoNota.pas' {Fr_CopiaPedidoNota},
  Un_RL_Reposicao in 'Relatorios\Un_RL_Reposicao.pas' {RL_Reposicao},
  sea_ctrl_estoque_zerado in 'Task\sea_ctrl_estoque_zerado.pas' {SeaCtrlEstoqueZerado},
  Un_Fatura_Fin in 'Tarefas\Un_Fatura_Fin.pas' {Fr_Fatura_Fin},
  tributacao in 'Componentes\tributacao.pas',
  sea_taxes in 'view\module\operation\register\sea_taxes.pas' {SeaTaxes},
  reg_taxes in 'view\module\operation\register\reg_taxes.pas' {RegTaxes},
  un_fm_lista_tax_incidency in 'Frames\un_fm_lista_tax_incidency.pas' {FmListaTaxIncidency: TFrame},
  un_fm_lista_class_trib_cbs_ibs in 'Frames\un_fm_lista_class_trib_cbs_ibs.pas' {FmListaClassTribIbsCbs: TFrame},
  un_fm_lista_cst_cbs_ibs in 'Frames\un_fm_lista_cst_cbs_ibs.pas' {FmListaCstCbsIbs: TFrame},
  ControllerIbscbs in 'Controller\ControllerIbscbs.pas',
  ControllerIbsMun in 'Controller\ControllerIbsMun.pas',
  tblIbsMun in 'model\tblIbsMun.pas',
  ControllerCbs in 'Controller\ControllerCbs.pas',
  tblCBS in 'model\tblCBS.pas',
  TblIbsCbs in 'model\TblIbsCbs.pas',
  ControllerIbscbsTribregular in 'Controller\ControllerIbscbsTribregular.pas',
  ControllerIbscbscredpres in 'Controller\ControllerIbscbscredpres.pas',
  tblIbscbscredpres in 'model\tblIbscbscredpres.pas',
  tblIbscbsTribcompraGov in 'model\tblIbscbsTribcompraGov.pas',
  ControllerIbscbsTribcompraGov in 'Controller\ControllerIbscbsTribcompraGov.pas',
  tblIbscbsMono in 'model\tblIbscbsMono.pas',
  ControllerIbscbsMono in 'Controller\ControllerIbscbsMono.pas',
  un_fm_lista_eventos_nfe in 'Frames\un_fm_lista_eventos_nfe.pas' {FmListaEventosNfe: TFrame},
  TblIbsCbsDif in 'model\TblIbsCbsDif.pas',
  TblIbsCbsRed in 'model\TblIbsCbsRed.pas',
  TblIbsCbsDevTrib in 'model\TblIbsCbsDevTrib.pas',
  ControllerIbsCbsDif in 'Controller\ControllerIbsCbsDif.pas',
  ControllerIbsCbsRed in 'Controller\ControllerIbsCbsRed.pas',
  ControllerIbsCbsDevTrib in 'Controller\ControllerIbsCbsDevTrib.pas',
  UN_Imp_Notas in 'Relatorios\UN_Imp_Notas.pas' {Fr_Imp_Notas},
  tblDistNfe in 'model\tblDistNfe.pas',
  tblDfeResumoNfe in 'model\tblDfeResumoNfe.pas',
  tblDfeResumoEvento in 'model\tblDfeResumoEvento.pas',
  tblDfeProtocolo in 'model\tblDfeProtocolo.pas',
  ControllerDistNfe in 'Controller\ControllerDistNfe.pas',
  ControllerDfeResumoNfe in 'Controller\ControllerDfeResumoNfe.pas',
  ControllerDfeResumoEvento in 'Controller\ControllerDfeResumoEvento.pas',
  ControllerDfeProtocolo in 'Controller\ControllerDfeProtocolo.pas',
  Un_Despacho in 'Tarefas\Un_Despacho.pas' {Fr_Despacho},
  Un_tr_send_email_login in 'Funcao\Un_tr_send_email_login.pas',
  Un_tr_send_email_estoque_negativo in 'Funcao\Un_tr_send_email_estoque_negativo.pas',
  ControllerDespacho in 'Controller\ControllerDespacho.pas';

{$R *.res}

begin
  {$IFDEF DEBUG}
  FullDebugModeScanMemoryPoolBeforeEveryOperation := True;
  ReportMemoryLeaksOnShutdown := True;
  SuppressMessageBoxes := FAlse;
  {$ENDIF}

  Application.Initialize;
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TDM_ListaConsultas, DM_ListaConsultas);
  Application.UpdateFormatSettings := False;
  // Define um padrão consistente (pt-BR)
  FormatSettings := TFormatSettings.Create('pt-BR');
  FormatSettings.DecimalSeparator   := ',';
  FormatSettings.ThousandSeparator  := '.';
  FormatSettings.CurrencyString     := 'R$';
  FormatSettings.CurrencyFormat     := 2; // R$ 1.234,56

  Application.Title := 'Gestão Empresarial';

  SplashForm := TSplashForm.Create(Application);
  SplashForm.Show;
  SplashForm.BringToFront;
  sleep(3000);
  SplashForm.Hide;
  Application.CreateForm(TFr_Principal, Fr_Principal);
  SplashForm.Close;
  FreeAndNil(SplashForm);

  Application.MainFormOnTaskbar := True;

  if Gb_exec_Aplication then
    Application.Run
  else
    winexec('taskkill /f /im Gestao.exe',sw_hide);

end.

